# Generated by Django 4.2 on 2026-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("activity", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=50)),
                (
                    "factor_kg_co2e",
                    models.DecimalField(decimal_places=8, max_digits=12),
                ),
                ("unit", models.CharField(max_length=20)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["category", "activity"],
            },
        ),
        migrations.CreateModel(
            name="UnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_unit", models.CharField(max_length=50)),
                ("to_unit", models.CharField(max_length=50)),
                ("factor", models.DecimalField(decimal_places=10, max_digits=18)),
            ],
            options={
                "unique_together": {("from_unit", "to_unit")},
            },
        ),
        migrations.AddIndex(
            model_name="emissionfactor",
            index=models.Index(
                fields=["category", "activity", "region"],
                name="factors_emi_categor_29539f_idx",
            ),
        ),
    ]
